#!/usr/bin/env bash
set -euo pipefail

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install

conda update conda -y
conda create -n py311 -c conda-forge python=3.11 pip -y
source $(conda info --base)/etc/profile.d/conda.sh
conda activate py311

pip3 install -e git+https://github.com/AllenNeuralDynamics/nmcp-precomputed@cba02c7698a60d500456dc98c5c618e15304dc13#egg=nmcp
pip3 install -e git+https://github.com/AllenNeuralDynamics/nmcp-scripting.git#egg=nmcpscripting
pip3 install zarr==2.18.2 \
"numpy<1.24" \
s3fs==2025.10.0 \
gql[requests]==3.5.2 \
openpyxl==3.1.5 \
pandas==1.5.3 \
boto3==1.40.49 \
aind-data-schema==2.0.4 \
matplotlib==3.10.7

echo "All done!"
