#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  ./run <raw-data-asset-uri> <s3-destination>
EOF
}

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
CREATE_METADATA_CMD=(
  python create_metadata.py "$1"
  --processing-json "/root/capsule/data/processing.json"
  --output-dir "/results"
)

"${CREATE_METADATA_CMD[@]}"

aws s3 cp --recursive --include "*.json" /results "$2"
